# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18ad112fdefc655d9a35d1edb3b1a295710541bc1c0994399edab28c61ec2801bbc29e97931bf8e2d347137e5392201063abdb4b94dc53f05cb00655073baef9

test:
  secret_key_base: 21642c64fd64398c13b079a2dc88893defe4ac1cf6c5654bcbc8b660407aef7790e4e70824ac9dc358bc588d5c71902dd7241daa03908ca8b19115a106763efc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
